### ISSUE TITLE
cannot find librealsense and openni2

### ISSUE THREAD

**Issue by wine3603** [fsrajer/LightLogger#1]
Hi man, I run cmake, got the error cannot find librealsense and openni2 even they are installed already,
are there any problem with the/cmake/FindRealSense.cmake ?

**Comment by fsrajer** [comment]
It is trying to find them in /usr/local. Simply set variables REALSENSE_ROOT and OPENNI2_ROOT if you have them elsewhere.

**Comment by SunshineDou** [comment]
Hello, Have you solved this problem? as I also run into this problem, but I have changed the directory of realsense and openni2, but it still failed, I don't know whether it is because the REALSENSE_ROOT and OPENNI2_ROOT directory I have changed is wrong. can you give me a hand where is the REALSENSE_ROOT and OPENNI2_ROOT .
Thank you very much!
